fix regression introduced by c7f7eaee
Fix failure introduced by new reliance on playbook_dir option:

[11/35] TC_Grapher#test_full = 0.01 s
  1) Error:
TC_Grapher#test_full:
TypeError: no implicit conversion of nil into String
    /home/adam/.GIT/3rd-party/ansible-viz/styler.rb:99:in `quote'
    /home/adam/.GIT/3rd-party/ansible-viz/styler.rb:99:in `block in decorate'
    /home/adam/.GIT/3rd-party/ansible-viz/styler.rb:88:in `each'
    /home/adam/.GIT/3rd-party/ansible-viz/styler.rb:88:in `decorate'
    /home/adam/.GIT/3rd-party/ansible-viz/grapher.rb:26:in `graph'
    /home/adam/.GIT/3rd-party/ansible-viz/ansible-viz.rb:99:in `render'
    /home/adam/.GIT/3rd-party/ansible-viz/test-grapher.rb:20:in `test_full'